service: lambda-hello-world

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
  defaultStage: development
  otherfile:
    environment:
      development: ${file(./config/development.yaml)}
      production: ${file(./config/production.yaml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom:defaultStage}
  region: ap-northeast-1

functions:
  helloWorld:
    handler: index.helloWorld
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
    environment:
      ENV: ${self:custom.otherfile.environment.${self:provider.stage}.ENV}

package:
  exclude:
    - node_modules/**
